version: '3.4'
services:
  db:
    container_name: company_management_db
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: 'company_management_db'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_ROOT_PASSWORD: ""
    volumes:
      - company_management_db_data:/var/lib/mysql
  app:
    container_name: company_management_project
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: 'company_management_project'
    ports:  
      - 8000:8000
    # command: sh docker/docker-entrypoint.sh
    volumes:
      - ./:/var/www/html
volumes:
  company_management_db_data: